name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3 # Updated to latest version

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to latest version
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          cd infrastructure
          npm ci
          cd ..

      # Build the application
      - name: Build root
        run: npm run build

      - name: Build infrastructure
        run: |
          cd infrastructure
          npm ci
          npm run build
          cd ..

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.NEXT_PUBLIC_CLOUD_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEXT_PUBLIC_CLOUD_ACCESS_KEY }}
          aws-region: us-east-2

      # Deploy infrastructure using AWS CDK
      - name: Deploy infrastructure
        run: |
          cd infrastructure
          npm ci
          npm run cdk deploy -- --require-approval never
